### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rgm89git** [valadaptive/ntsc-rs#121]
I've shared the project on a open-source community and they noted the lack of license.

If you want to add a license of the source code of **ntsc-rs**, what do you choose?

**Comment by valadaptive** [comment]
There are SPDX license identifiers listed in the crates, but they're admittedly hard to find. The licensing situation is tricky because the effect itself is dual MIT/Apache licensed, but the GUI has to be GPL licensed because it uses some GPL-licensed codecs.

I'll try to set up some licenses in a hopefully-clear way that GitHub's automated license detection picks up on, while clearly differentiating the different components' different licenses.

**Comment by rgm89git** [comment]
Ok.

**Comment by valadaptive** [comment]
I think this is done now--let me know if you have further questions
