### ISSUE TITLE
What's taken you so long?

### ISSUE THREAD

**Issue by TheGithubberpng** [valadaptive/ntsc-rs#138]
When will 0.8.0 come out?

**Comment by nlolnlolnlolnlo** [comment]
this seems like a fairly demanding message.

it would be good to consider that this is a free project with 90% of the function and effects already implemented. you should also consider that there's only one developer working on the program and she's likely working on other projects as well. i think a little bit of patience would go a long way.

**Comment by valadaptive** [comment]
Right now, the main obstacle is figuring out the best way to distribute the macOS plugins--either by simply telling users the (somewhat involved) process for loading unsigned plugins in Resolve and After Effects, or creating some sort of installer that manages it for them (if such a thing is even possible).

Before that, most of it was cleaning up various code that's been lingering around since the beginning of the project almost a year ago. A lot of code has been changed or rewritten since v0.7.3 as a result of these cleanups, and I've updated a few libraries which has also required some changes, so I've also been making sure I haven't introduced any regressions.

I've also been trying to test and ensure the stability of the completely-rewritten After Effects plugin. It was previously written in C, but over the past year there's been a lot of development on [Rust bindings for the After Effects API](https://github.com/AdrianEddy/after-effects/), so I've rewritten it in Rust using those. The After Effects plugin has seen [a](https://github.com/valadaptive/ntsc-rs/commit/b59dd24c02eadd4afe4e00c0272178f75fea9170) [huge](https://github.com/valadaptive/ntsc-rs/commit/413c25b215fbab48dd2b1b43c15d5588e86b6292) [number](https://github.com/valadaptive/ntsc-rs/commit/0091b3b7912d9f6149cf57de0b3211d316d01c0c) [of](https://github.com/valadaptive/ntsc-rs/commit/a2f9aa2ed9033fa6529359834713f7de9748a67b) [bugs](https://github.com/valadaptive/ntsc-rs/commit/b77f08e2653db57cb67c60ac9ab3bb5894ca4f5c) [and](https://github.com/valadaptive/ntsc-rs/commit/bf9c6bfcca58b593f57cb312d083ff97b59b0044) [regressions](https://github.com/valadaptive/ntsc-rs/commit/66cd8a79a4123d2d825e959ffa8fc076ff2d3506), and I want to avoid creating more.

I've been focusing most of my attention elsewhere for the past week, working on other open-source projects, but I'm still working on ntsc-rs.

**Comment by TheGithubberpng** [comment]
oh ok

**Comment by Degamisu** [comment]
Better not to rush it! Good luck on your other projects.

**Comment by valadaptive** [comment]
v0.8.0 has been released.
