### ISSUE TITLE
entry point not found

### ISSUE THREAD

**Issue by thad4002** [valadaptive/ntsc-rs#154]
ok so i tried opening ntsc-rs-standalone.exe, and then this happened:
![image](https://github.com/user-attachments/assets/5d18e3d7-7cb8-4572-b525-cfec0b309d76)

**Comment by valadaptive** [comment]
It looks like you're using Windows 7, which has [reached end-of-life and is no longer receiving security updates since 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962). ntsc-rs does not support Windows 7.

This is not unique to ntsc-rs; most software, including every major web browser, has also dropped support for Windows 7. I would strongly recommend upgrading to Windows 11, or Windows 10 if your computer doesn't support 11.
