### ISSUE TITLE
(suggestion) add multi languages suport?

### ISSUE THREAD

**Issue by SecondIces** [valadaptive/ntsc-rs#18]
because original ntscqt has Russian language.
and i want to add Chinese language.

**Comment by zzzzzz9125** [comment]
I don't know much else, but I can offer my knowledge of OFX plugin translation for Vegas Pro.

First of all, I've added a Chinese translation of NTSC-rs OFX for Vegas Pro, and it doesn't seem to work in other softwares. Anyway, I'll upload it here: [NtscRs.zh-CN.zip](https://github.com/valadaptive/ntsc-rs/files/15142216/NtscRs.zh-CN.zip).

Place the `NtscRs.zh-CN.xml` into `...\NtscRs.ofx.bundle\Contents\Resources\NtscRs.zh-CN.xml`, then when you're running the Chinese version of Vegas Pro, this file will be read and used.

Similarly, other languages can be supported by the following files: `NtscRs.de-DE.xml`, `NtscRs.es-ES.xml`, `NtscRs.fr-FR.xml`, `NtscRs.ja-JP.xml`, `NtscRs.ko-KR.xml`, `NtscRs.pl-PL.xml`, `NtscRs.pt-BR.xml`.

`NtscRs.xml` is also an acceptable one and is generally used to store the original English texts. It can also be used as a test, such as renaming `NtscRs.zh-CN.xml` to `NtscRs.xml`, so that it will be an alternate option in any language version of Vegas Pro.

Maybe there's a better way to make translation files common to other OFX hosts? I haven't looked into it...

**Comment by valadaptive** [comment]
I abandoned this idea a while ago because of the complexity:
- Translating every string for the core ntsc-rs settings
- Also doing it for everything in the GUI
- Working with the bespoke internationalization APIs for After Effects and each specific OpenFX host
- Hosting a server for crowdsourcing translations and keeping it running
- Keeping all the translations up-to-date as volunteers come and go

I may come back to this at some point in the far future, but right now it doesn't seem very feasible with the resources I have available.
