### ISSUE TITLE
White Balance feature

### ISSUE THREAD

**Issue by hung514** [valadaptive/ntsc-rs#184]
as I'm testing with the latest version of ntsc-rs, I wonder if there was a white balance feature? So, I'll give you a sample on what Im using.

![Coolcolor_Test](https://github.com/user-attachments/assets/f4896b69-cadd-4187-8749-c6041885ed31)
**Image 1** (_Cool_)

![Warmcolor_Test](https://github.com/user-attachments/assets/3442800b-e2fd-48c2-a0a4-3fb97e8a708a)
**Image 2** (_Warm_)

im not sure about choosing the link, but here is something similar. 
https://www.avartifactatlas.com/artifacts/white_balance_error.html

(Also, I'm kinda new and never communicate here before, so please be mindful about it)

**Comment by valadaptive** [comment]
As the linked page says, white balance error is caused by the camera itself, not the recording medium. It falls outside of what ntsc-rs attempts to emulate.

If you want to emulate white balance error, you can use editing software to apply a separate white balance effect and then apply ntsc-rs on top of it. I'd recommend DaVinci Resolve--it's free and supports OpenFX plugins, which includes ntsc-rs.

**Comment by hung514** [comment]
shouldve chose the correct link, but ok (also, hi valadaptive. never actually see you before, but hello)
