### ISSUE TITLE
Can't run on Linux Mint 21.3

### ISSUE THREAD

**Issue by herrobriam** [valadaptive/ntsc-rs#215]
basically, since there's no glib 2.39 it can't run:

`./ntsc-rs-standalone: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./ntsc-rs-standalone)
./ntsc-rs-standalone: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by ./ntsc-rs-standalone)`

and compiling glib 2.39 doesnt work either as i can't seem to get patchelf to patch it properly without random errors

**Comment by valadaptive** [comment]
Seems like Linux Mint 21.3 is based on Ubuntu 22.04, whereas I was building ntsc-rs in GitHub Actions on Ubuntu 24.04.

The next release should fix this, but in the meantime you can either upgrade to Linux Mint 22 or [build ntsc-rs from source](https://ntsc.rs/docs/building-from-source/). It should be easier on Linux than on Windows because you can install all the necessary GStreamer stuff from your package manager.

**Comment by valadaptive** [comment]
This has been fixed in v0.9.0.
