### ISSUE TITLE
help 😭

### ISSUE THREAD

**Issue by 23113ver** [valadaptive/ntsc-rs#240]
@valadaptive **wtf is “cannot execute file.”? im on windows 7 but this is not my main pc because i tested ntscrs early and it worked (i accidentally deleted ntscrs)****

**Comment by valadaptive** [comment]
Windows 7 has [reached end-of-life and is no longer receiving security updates since 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962). ntsc-rs does not support Windows 7.

This is not unique to ntsc-rs; most software, including **every major web browser**, has also dropped support for Windows 7. I would strongly recommend upgrading to Windows 11, or Windows 10 if your computer doesn't support 11. I know newer versions of Windows kinda suck, but it's better than using a version of Windows with unpatched security vulnerabilities that can only run web browsers that also have unpatched security vulnerabilities.

**Comment by 23113ver** [comment]
i mean win7 is not my main pc, but ok
