### ISSUE TITLE
Export to bmp sequence?

### ISSUE THREAD

**Issue by ElijahHamilton** [valadaptive/ntsc-rs#94]
Hi, exporting the video as a bmp sequence is much faster than using the mp4 encoder.

**Comment by valadaptive** [comment]
I can't really implement .bmp rendering, both because GStreamer doesn't really support it (the ffmpeg plugin does, but seems to have trouble rendering image sequences) and because uncompressed video data is *huge* (about 1MB per frame for 480p video).

I *can* implement PNG sequence rendering, but even with compression disabled, it's a bit slower than H.264 with the maximum encoding speed and quality at 50 (lossless). What are you using as a reference for your speed comparison?

**Comment by ElijahHamilton** [comment]
I was just running the windows build and exporting to mp4. I didn't have the output resolution too high (around 300px width)

**Comment by valadaptive** [comment]
I mean, what you using as a reference point to compare the speed of a .bmp sequence and .mp4 encoding? (e.g. other software that can render both, and that you have noticed a speedup in).

How long does H.264 rendering take if you set the "Encoding speed" slider to 8?

**Comment by nlolnlolnlolnlo** [comment]
probably more economical to render as ffv1 (lossless) and just use ffmpeg to split to an image sequence

`ffmpeg -i in-ffv1.mkv img%04d.bmp`

**Comment by valadaptive** [comment]
I've done some testing and it seems ffv1 is much slower than x264. I may look into adding HuffYUV support.

**Comment by valadaptive** [comment]
Never mind; seems like the ffv1 codec requires multithreading to be manually enabled. It should be on par with h.264 in the next release.

**Comment by valadaptive** [comment]
@ElijahHamilton Try downloading the latest version. Is either H.264 or FFV1 fast enough for your needs?

And again, how are you comparing the speed of .bmp rendering to .mp4 rendering? Is this based on other software?
